### ISSUE TITLE
Wallpaper?

### ISSUE THREAD

**Issue by willjet73** [Jack-LP/gruvbox-glass#1]
Hi this isnt really an issue, but what wallpaper are you using on the Gruvbos Glass vscode theme photos? Thanks lol
![image](https://user-images.githubusercontent.com/78431472/167312830-a74a0e6f-0a04-4bd2-a276-7914e1513226.png)

**Comment by Jack-LP** [comment]
Hi, sorry for late response
It's a live wallpaper from wallpaper engine - https://steamcommunity.com/sharedfiles/filedetails/?id=1214148605
The wallpaper's source video is [here](https://youtu.be/v8XNDsXxLwE)

**Comment by willjet73** [comment]
Thanks

**Comment by willjet73** [comment]
Thanks!
